version: "3.6"
services:
  jupyter_lab_cpu:
    container_name: "jupyter-lab-cpu"
    restart: unless-stopped
    image: wolodin/jupyter_lab_cpu:latest
    volumes:
      - ./lessons:/home/web/lessons:rw,cached
    user: ${HOST_USER_ID:-1000}:${HOST_GROUP_ID:-1000}
    ports:
      - "127.0.0.1:8888:8765"
      - "127.0.0.1:6006:6006"
    networks:
      - webnet

networks:
  webnet:
